// Generated by scripts/fetch-aws-icons.mjs — do not edit by hand.
// AWS Architecture Icons release: 07312026
import type { NodeType } from '@cloudatlas/shared'

export type AwsIconStyle = 'service' | 'resource'

export interface AwsIcon {
  /** Path under apps/web/public. */
  src: string
  style: AwsIconStyle
}

export const AWS_ICON_RELEASE = '07312026'

export const AWS_ICONS: Partial<Record<NodeType, AwsIcon>> = {
  ec2: { src: '/aws-icons/ec2.svg', style: 'service' },
  lambda: { src: '/aws-icons/lambda.svg', style: 'service' },
  'ecs-task': { src: '/aws-icons/ecs-task.svg', style: 'service' },
  'ecs-service': { src: '/aws-icons/ecs-service.svg', style: 'service' },
  alb: { src: '/aws-icons/alb.svg', style: 'resource' },
  nlb: { src: '/aws-icons/nlb.svg', style: 'resource' },
  'target-group': { src: '/aws-icons/target-group.svg', style: 'service' },
  'nat-gateway': { src: '/aws-icons/nat-gateway.svg', style: 'resource' },
  'internet-gateway': { src: '/aws-icons/internet-gateway.svg', style: 'resource' },
  eni: { src: '/aws-icons/eni.svg', style: 'resource' },
  'vpc-endpoint': { src: '/aws-icons/vpc-endpoint.svg', style: 'resource' },
  cloudfront: { src: '/aws-icons/cloudfront.svg', style: 'service' },
  'route53-zone': { src: '/aws-icons/route53-zone.svg', style: 'service' },
  vpc: { src: '/aws-icons/vpc.svg', style: 'service' },
  rds: { src: '/aws-icons/rds.svg', style: 'service' },
  'rds-cluster': { src: '/aws-icons/rds-cluster.svg', style: 'service' },
  elasticache: { src: '/aws-icons/elasticache.svg', style: 'service' },
  s3: { src: '/aws-icons/s3.svg', style: 'service' },
  'ebs-volume': { src: '/aws-icons/ebs-volume.svg', style: 'service' },
  sqs: { src: '/aws-icons/sqs.svg', style: 'service' },
  sns: { src: '/aws-icons/sns.svg', style: 'service' },
  'eventbridge-rule': { src: '/aws-icons/eventbridge-rule.svg', style: 'service' },
  'waf-web-acl': { src: '/aws-icons/waf-web-acl.svg', style: 'service' },
  'network-firewall': { src: '/aws-icons/network-firewall.svg', style: 'service' },
  'iam-role': { src: '/aws-icons/iam-role.svg', style: 'service' },
}
